version: '3'

services:
  prod:
    image: lambci/lambda-base
    links:
      - db
    depends_on:
      - db
    env_file:
      - lendr.env
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./build/main:/main
    entrypoint:
      - /main
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
