// Code generated by hero.
// source: golend/internal/json/LendableCreationDialog.json
// DO NOT EDIT!
package template

import (
	"io"

	"github.com/shiyanhui/hero"
)

func LendableCreationDialog(Counts []int, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`
{
  "title":        "What is your thing?",
  "submit_label": "Submit",
  "callback_id":  "manage.create_thing",
  "elements":     [
    {
      "type":  "text",
      "label": "Name",
      "name":  "thing_name"
    },
    {
      "label":   "Related",
      "type":    "select",
      "name":    "relates_to",
      "options": [
        `)
	for _, val := range Counts {
		_buffer.WriteString(`
        {
          "label": "Parent (probably the one you want)",
          "value": "`)
		hero.FormatInt(int64(val), _buffer)
		_buffer.WriteString(`"
        },
        `)
	}
	_buffer.WriteString(`
      ]
    },
    {
      "label":   "Control Access",
      "type":    "select",
      "name":    "control_access",
      "options": [
        `)
	for _, val := range Counts {
		_buffer.WriteString(`
        {
          "label": "Parent (probably the one you want)",
          "value": "`)
		hero.FormatInt(int64(val), _buffer)
		_buffer.WriteString(`"
        },
        `)
	}
	_buffer.WriteString(`
      ]
    }
  ]
}
`)
	w.Write(_buffer.Bytes())

}
